### ISSUE TITLE
Merging SeisIO.jl and Seis.jl

### ISSUE THREAD

**Issue by mdenolle** [jpjones76/SeisIO.jl#5]
Hello JP Jones.
We are a team trying to build similar tools for ambient noise correlation work. With Andy Nowacki (https://github.com/anowacki) we are trying to build a module that is similar to Obspy but for Julia. Both his Seis and SeisRequests and your SeisIO modules have functionalities that we are interested in, namely:
- SeisRequests.jl can handle wildcards and removing instrumental response, has nice functionalities to download from multiple servers.
- SeisIO has nice data structure, good downloading, and great read/writes of format.

Is there any chance we could chat with you about importing some of the functionality from your module into Seis.jl (https://github.com/anowacki/Seis.jl)? happy to make one module that accommodates all needs. We are also developing HDF5/ASDF formats.

Cheers,
Marine

**Comment by jpjones76** [comment]
Hi Marine,

I like the idea, but I need more information about the scope and goals of Seis.jl, e.g.,

* What are your plans for development? 
* Which analysis routines are current? Which are planned?
* How many contributors do you have? How many do you intend to have at maximum?
* What are the advantages of SeisRequests over SeisIO with respect to wildcards, instrument response, and data downloading? (I've had routines that do all three since 2016, though instrument response for passive geophones only, because that's all I use at present)
* Who funds the work? 

As a brief background, when I created SeisIO in May 2016, there was no seismic data architecture for Julia; there was SacIO.jl by Ben Postlethwaite for SAC, plus a SEG Y reader in the U. Alberta reflection seismology module. My goal was (and is) a streamlined data architecture with a simple file format: speed and intuitive UX, with the ability to read as many geophysical file formats as possible. So, before I could agree to anything, I'd need to know what parts of SeisIO will be used and how.

Thanks,
Josh

**Comment by mdenolle** [comment]
Hi Josh,

Thank you for the prompt response! I'd like to correspond via email, you can reach me at mdenolle at fas.harvard.edu.
Cheers,
Marine

**Comment by mdenolle** [comment]
Hi Josh,

I would like to pursue this conversation via email, would you be able to find my address from my work affiliation?
Cheers,
Marine

**Comment by jpjones76** [comment]
Email sent! Let's talk more there.

**Comment by anowacki** [comment]
Hi both,

Apologies for not noticing this earlier, and sorry if this came out of the blue.  I had been slowly chipping away at [Seis.jl](https://github.com/anowacki/Seis.jl) before actively engaging with the wider seismic Julian world, and then Marine got in touch.  I had not really intended to start using Seis.jl in anger and still feel much is up for grabs.  It's an attempt to learn the lessons from [SAC.jl](https://github.com/anowacki/SAC.jl) and take the opportunity to change it for Julia v1.0.  For my day-to-day processing, I'm in the process of moving from SAC.jl to Seis.jl, but still want to see whether the community can coalesce around something for the long term.

(SAC.jl has been going since [2015](https://github.com/anowacki/SAC.jl/commit/c66cae383b156d8638e0515d0ade8d15d475baf6) and is in use at least at MIT and UNAM (Mexico), the latter for teaching.)

My end goal is to get to a community-supported Julia passive seismic package that does what we need well (see [here](https://github.com/anowacki/Seis.jl/blob/master/Seis.jl.md)).  I'm not totally wedded to any one design, but with Marine's work we have an opportunity to try to get to something from real-world experience which my own research doesn't address (i.e., noise and very long time series).

To answer your questions:

- Plans for development:
  - Open development.  Seis.jl could be the foundation, but so could SeisIO.jl.
  - For Seis.jl itself, in the short term, I plan to make it at least functionally equivalent to SAC.jl.
  - I believe Marine's group are using Seis.jl as a base for now.
- Analysis:
  - All routines in SAC.jl will eventually be ported—that's easy
  - I have local beamforming/array processing codes that will be merged.
  - Anything else needed should interact with this Julian seismology ecosystem we're building in the end!  [This](https://github.com/anowacki/Seis.jl/blob/master/Seis.jl.md) is meant as a starting point for what's in scope for Seis.jl, but as I say, the final details are up for grabs.
- Contributors:
  - Marine and me at the moment—more welcome, and I don't see an upper limit as an open-source project.
- Advantages of SeisRequests
  - Honestly, I don't know there are many.  I wrote this before realising that SeisIO had similar functionality.
  - Possibly the only advantage is that right now the StationXML specification is implemented in [StationXML.jl](https://github.com/anowacki/StationXML.jl) and so the full StationXML formatted output of a station query can be ingested ready for future use.  The same isn't true yet for QuakeML (but is planned) for earthquake data.
- Funding
  - My own research grants, and Marine's I believe.
  - We could look to software development funding in the future—I had a software engineering project in the past which provided investigator time.

I would be very happy to continue this conversation offline as well.

**Comment by jpjones76** [comment]
Hi Andy,

I'm very sorry for stepping on your toes about SAC functionality. I'm willing to rewrite SeisIO to use SAC.jl as a dependency, but I'd like to do some benchmark tests first. 

My goals for SeisIO are very basic:
- Fast, efficient data i/o
- Broad support for univariate geophysical data formats
- Native file i/o that performs well at scale
- Intuitive UX with no bloat

The last item is why I have very few fields in each data type; most users don't need the fine-grained field definitions of e.g., SEG Y, and for non-seismic data the field abbreviations quickly become ambiguous.

I'd be happy to use SeisIO as the basis of other packages, though, and can make modifications provided that the core data types remain backwards-compatible. I've thought about a major overhaul to optimize the "data" field (`S.x`) for distributed computing, but the data type needed is a turgid union of arrays or  DistributedArrays.jl, which isn't yet stable.

Honestly, I didn't know that SAC.jl existed in 2016, or I would've coded with it as a dependency. When I started SeisIO, I searched for Julian seismology packages and found only two: SacIO by @bpostlethwaite and one from a U. Alberta group. SacIO was abandoned 2013 but the creator gave me permission to take over via. email. I think I briefly used his code, but switched because Julia improved string handling.

Your StationXML.jl looks excellent. I think my web requests do similar things to SeisRequests aside from that, with a working SeedLink client. In theory I could incorporate StationXML.jl as a dependency, but FDSN StationXML is station-oriented, rather than channel-oriented.

I have concerns about creating a single large ObsPy-type project with many contributors, but that's best discussed by email.

**Comment by anowacki** [comment]
Hi Josh,

No need to apologise—I think there's plenty of room for multiple Julia packages dealing with SAC data.  I'm certain that SAC.jl isn't optimised for your uses, and I think SeisIO does its job very nicely without needing to depend on SAC.jl—it's such a basic format after all.  (Interestingly in my speed profiling, SAC.jl—and so will SeisIO I guess—outperforms SAC on reading and writing SAC data!)  In any case, I plan to deprecate SAC.jl once Seis.jl is up and running.  So not using SAC.jl back in 2016 was probably the right decision in any case!

I don't think merging efforts is necessarily the way to go here.  SeisIO could be a great base for IO within a larger package, I guess, and I see exactly your goals with it.  I think there is a general appetite out there for a bells-and-whistles package/ecosystem (look at the success of ObsPy) so I'm aiming more in that direction.  So the goals of the two packages are obviously different, and that's fine in my opinion.

One future option I've been thinking about is to have a SeisBase.jl package which just defines the structures, and on top of that is built the rest of the ecosystem.  Then your suggestion of updating the fields within SeisIO might come into play.  The initial design of `Trace` is Seis.jl is meant to be similar, but I let you chuck in anything you like in a `.meta` dictionary field.  But we're straying far from SeisIO in a SeisIO issue, so I think it's best to continue this elsewhere, like you say.

I can't find your email address, but mine is on my GitHub user page.

**Comment by jpjones76** [comment]
I'm going to close this issue since we all have each other's email addresses now. Thanks again and let's continue the discussion there!
